version: '3.8'

services:
  app:
    build:
      context: /opt/lampp/htdocs/servet
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_PATH=/tmp/yemek_sitesi.db
